# scripts/validate_targets.py
"""
Validasi targets.yaml secara standalone.
Jalankan via GitHub Actions atau manual. Exit code:
  0 = valid
  1 = tidak valid / file bermasalah
"""
from __future__ import annotations
import sys
from pathlib import Path

# Pastikan root proyek ada di path, biar `import src.xxx` jalan
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import yaml  # noqa: E402

from src.targets_loader import load_targets, TargetsValidationError  # noqa: E402


def main() -> int:
    try:
        cfg = load_targets("targets.yaml")
    except FileNotFoundError as e:
        print(f"❌ {e}")
        return 1
    except yaml.YAMLError as e:
        print(f"❌ Sintaks YAML rusak:\n{e}")
        return 1
    except TargetsValidationError as e:
        print(f"❌ {e}")
        return 1

    # Sukses — tampilkan ringkasan biar lo yakin isinya kebaca bener
    print("✅ targets.yaml VALID\n")
    print(f"   Generated by : {cfg.generated_by}")
    print(f"   Version      : {cfg.version}")
    print(f"   Kategori     : {len(cfg.categories)}")
    print(f"   Total target : {cfg.total_targets}\n")

    for cat in cfg.categories:
        print(f"   ▸ [{cat.niche}] {cat.name} — {len(cat.targets)} target")
        for t in cat.targets:
            extra = f"  ({', '.join(f'{k}={v}' for k, v in t.extra.items())})" if t.extra else ""
            print(f"       - {t.domain}{extra}")
        print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
